version: '2'

networks:
  default:
    external:
      name: latelier

services:
  tableau-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        proxy: ${http_proxy}
        no_proxy: "127.0.0.1,localhost,tableau-server,tableau"
        TABLEAU_VERSION: ${TABLEAU_VERSION}
        TSM_PASSWORD: ${TSM_PASSWORD}
        ADMIN_PASSWORD: ${TSM_PASSWORD}
    image: tableau-server
    container_name: tableau-server
    volumes:
      - ./data:/var/opt/tableau
      - ./config:/opt/tableau/docker_build/
      - ./run:/run
      - ./log:/var/log
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "8080:80"
      - "8085:8085"
    privileged: true
    
